version: '3.8'

services:
  controlapi:
    container_name: controlbroker
    networks:
      - mynetwork
    build:
      context: ./ControlBroker
      dockerfile: Dockerfile    
    ports:
      - 8001:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ASPNETCORE_URLS=http://+'
    stdin_open: true
    tty: true

  nginx:
    container_name: my_nginx_rtmp
    ports:
      - 1935:1935
      - 7777:7777
    networks:
      - mynetwork
    build:
      context: ./StreamingServer
      dockerfile: Dockerfile

  aivision:
    container_name: aivision
    build:
      context: ./AIVisionProcessing
      dockerfile: Dockerfile
    networks:
      - mynetwork
    command:
      --source="rtmp://nginx/stream/stream"
      --weights="drone_gestures.pt"
      --process-connection
      # --show-preview #we should not pass this argument because container doesn't have possibility to display anything
 
  ngrok2:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040   
    networks:
      - mynetwork     
networks:
  mynetwork:
    driver: bridge
